### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by gsklee** [redux-utilities/redux-promise#19]
Please add some more comprehensive examples.

**Comment by eriknyk** [comment]
+1

**Comment by aniss** [comment]
+1

**Comment by mauriciosoares** [comment]
+1

**Comment by jingzhou123** [comment]
+1

**Comment by jjzazuet** [comment]
+1

**Comment by drhayes** [comment]
Here are some things that confuse me:

Let's say I have a function that returns a Promise for fetching the user's profile, called `fetchUser`. If I do this: `dispatch.setUser(fetchUser());` then `redux-promise` handles everything, including if the Promise rejects. Great!

Now I have dependent actions. Based on something in the user profile I need to get something else. Now what? I end up with code that looks like this:

```
function fetchUser() {
  // return a Promise...
}

function unwrapAction() {
  if (action.error) { throw action.payload; }
  return action.payload;
}

setUser(fetchUser())
  .then(unwrapAction)
  .then(user => dispatch(fetchEmailsForUser(user))
  .catch(e => dispatch(notifyUser(e.message)));
```

That interstitial `unwrapAction` things seems clumsy and makes me feel like I'm missing the point somewhere. AFAICT it needs to be there because dispatch is handing back the action I'm passing in and errors are properties of the action. If I don't do that my promise chain swallows errors that don't bounce through the store. That doesn't seem great either.

**Comment by cncolder** [comment]
I think this module is design for work with [redux-actions](https://github.com/acdlite/redux-actions) together.

```javascript
    // actions/login-user.js
    export const loginUser = createAction('LOGIN_USER', api.postLoginUser)
```

```javascript
    // utils/api.js
    // this return promise, you can use another e.g. fetch()
    export const postLoginUser = user => socket.postAsync('/auth/login', user)
```

```javascript
    // reducers/login.js
    const login = handleActions({
      LOGIN_USER: {
        next: (state, action) => ({
          username: '',
          password: '',
          error: {},
        }),
        throw: (state, action) => ({
          ...state,
          error: action.payload,
        }),
      },
    }, {
      username: '',
      password: '',
      error: {},
    })
```

**Comment by waynelkh** [comment]
@cncolder thanks for your example.
How can I dispatch trigger an action to change `{ isLoading: false }` to `{ isLoading: false }` state ?

**Comment by cncolder** [comment]
@waynelkh redux-promise only dispatch one action after promise resolved. So I have no another better idea.

**Comment by code-by** [comment]
Any simple example when "If it receives a promise, it will dispatch the resolved value of the promise. It will not dispatch anything if the promise rejects." please )

**Comment by acpower7** [comment]
+1
